/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf9f6",
        "tertiary-dim": "#674f30",
        "background": "#fbf9f6",
        "on-surface": "#30332f",
        "inverse-primary": "#ffffff",
        "surface-dim": "#d9dbd4",
        "on-tertiary": "#fff7f3",
        "error": "#9f403d",
        "inverse-surface": "#0e0e0d",
        "on-primary-fixed": "#3f3f3f",
        "on-primary": "#faf7f6",
        "tertiary": "#745b3b",
        "surface-container-high": "#e8e8e3",
        "on-tertiary-fixed-variant": "#6e5536",
        "secondary-fixed-dim": "#bfd9de",
        "on-primary-container": "#525151",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeea",
        "on-secondary-fixed": "#2b4347",
        "on-secondary-fixed-variant": "#486063",
        "on-error": "#fff7f6",
        "primary": "#5f5e5e",
        "tertiary-fixed": "#fddab2",
        "on-primary-fixed-variant": "#5c5b5b",
        "outline-variant": "#b1b3ad",
        "on-surface-variant": "#5d605b",
        "on-background": "#30332f",
        "surface-variant": "#e2e3dd",
        "secondary-fixed": "#cde7ec",
        "surface-container-low": "#f5f3f0",
        "tertiary-fixed-dim": "#eecca5",
        "secondary-dim": "#3f575b",
        "inverse-on-surface": "#9e9d9a",
        "primary-dim": "#535252",
        "on-secondary-container": "#3e565a",
        "on-error-container": "#752121",
        "primary-fixed": "#e4e2e1",
        "surface": "#fbf9f6",
        "outline": "#797b77",
        "on-tertiary-container": "#634c2d",
        "error-dim": "#4e0309",
        "error-container": "#fe8983",
        "primary-container": "#e4e2e1",
        "on-secondary": "#ebfcff",
        "secondary": "#4b6367",
        "on-tertiary-fixed": "#4f391d",
        "secondary-container": "#cde7ec",
        "surface-tint": "#5f5e5e",
        "primary-fixed-dim": "#d6d4d3",
        "surface-container-highest": "#e2e3dd",
        "tertiary-container": "#fddab2"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Newsreader", "serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0rem", 
        "lg": "0rem", 
        "xl": "0rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
